version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      # MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: sample_db
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
      TZ: 'Asia/Tokyo'  # タイムゾーンを日本時間に設定
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3308:3308
    command: --port 3308
    tty: true
    networks:
      - local-net
  app:
    depends_on:
      - db
    build:
      context: .
    volumes:
      - .:/app:rw
    command:
      sh -c "python3 main.py"
    ports:
      - "8000:8000"
    networks:
      - local-net
networks:
  local-net:
    driver: bridge
